### ISSUE TITLE
添加IPv6 DNS检测

### ISSUE THREAD

**Issue by fcwys** [Kukaina/DnsTools#4]
希望添加添加IPv6 DNS检测，使用标识或TAB页分类IPv4和IPv6 DNS列表，谢谢！

**Comment by Kukaina** [comment]
> 希望添加添加IPv6 DNS检测，使用标识或TAB页分类IPv4和IPv6 DNS列表，谢谢！

可以的，很容易加个json就行，今天推1.2.1就加上，但必须本机有IPV6

**Comment by fcwys** [comment]
非常感谢，因为现在IPv6已经很普及了

**Comment by Kukaina** [comment]
> 非常感谢，因为现在IPv6已经很普及了，如果可以的话加上一个标识或者TAB分类会更好
已经更新了
