### ISSUE TITLE
为什么不能使用ctrl加-/+来缩小文字和控件呢？

### ISSUE THREAD

**Issue by Holocure** [Kukaina/DnsTools#6]
因为显示器摆放距离的原因，我将字体显示调成了150%，这样windows的各项字体大小都方便阅读。但是像webview和electron应用很容易出现字体太大，都挤到一起很难看的问题，需要单独调节下。请问是tauri不支持这个快捷键吗？

**Comment by Holocure** [comment]
感谢回复，我去tauri那里反馈下

**Comment by Holocure** [comment]
作者大大，看看这个issue[https://github.com/tauri-apps/tauri/issues/3310#issue-1118688006](url)

**Comment by Kukaina** [comment]
> 作者大大，看看这个issue[https://github.com/tauri-apps/tauri/issues/3310#issue-1118688006](url)

<iframe src="https://onedrive.live.com/embed?resid=F770018B695998C2%21249&authkey=!AGcbG8GKKe0W6Yg" width="98" height="120" frameborder="0" scrolling="no"></iframe>这样可以吗

**Comment by Kukaina** [comment]
https://github.com/Kukaina/DnsTools/assets/149920301/c00257b4-1223-41b5-b92a-73b835edced2

这样这样可以吗

**Comment by Holocure** [comment]
太棒

> 2024-02-20.14-59-21.mp4 
> 这样这样可以吗

太棒了！！！感谢😍😍
请问可以告诉我怎么实现的吗（方便其他作者修改）？

**Comment by Kukaina** [comment]
> 太棒
> 
> > 2024-02-20.14-59-21.mp4
> > 这样这样可以吗
> 
> 太棒了！！！感谢😍😍 请问可以告诉我怎么实现的吗（方便其他作者修改）？

就是issue里面提到的，然后用pinia做一下持久化再监听一下快捷键
`document.body.style.zoom=settings.zoom
// 监听键盘事件
document.addEventListener('keydown', function(event) {
    // 检查是否同时按下了Ctrl（Cmd）和'+'或'-'键
    if (event.ctrlKey || event.metaKey) { // 在Mac上使用metaKey代替ctrlKey
        const zoomIn = event.key === '=';
        const zoomOut = event.key === '-';

        if (zoomIn || zoomOut) {
            // 防止默认行为，比如在输入框中输入'+'或'-'
            event.preventDefault();

            // 放大或缩小
            if (zoomIn) {
                settings.zoom += 0.1; // 放大10%
            } else if (zoomOut) {
                 settings.zoom-= 0.1; // 缩小10%
            }

            // 设置新的缩放级别
            document.body.style.zoom = settings.zoom;
        }
    }
});`
